/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CreateRouteImport } from './routes/create'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RSlugIndexRouteImport } from './routes/r/$slug/index'
import { Route as RSlugEditRouteImport } from './routes/r/$slug/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugIndexRoute = RSlugIndexRouteImport.update({
  id: '/r/$slug/',
  path: '/r/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugEditRoute = RSlugEditRouteImport.update({
  id: '/r/$slug/edit',
  path: '/r/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/r/$slug/edit': typeof RSlugEditRoute
  '/r/$slug/': typeof RSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/r/$slug/edit': typeof RSlugEditRoute
  '/r/$slug': typeof RSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/r/$slug/edit': typeof RSlugEditRoute
  '/r/$slug/': typeof RSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/account' | '/create' | '/login' | '/r/$slug/edit' | '/r/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/create' | '/login' | '/r/$slug/edit' | '/r/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/create'
    | '/login'
    | '/r/$slug/edit'
    | '/r/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CreateRoute: typeof CreateRoute
  LoginRoute: typeof LoginRoute
  RSlugEditRoute: typeof RSlugEditRoute
  RSlugIndexRoute: typeof RSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug/': {
      id: '/r/$slug/'
      path: '/r/$slug'
      fullPath: '/r/$slug/'
      preLoaderRoute: typeof RSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug/edit': {
      id: '/r/$slug/edit'
      path: '/r/$slug/edit'
      fullPath: '/r/$slug/edit'
      preLoaderRoute: typeof RSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CreateRoute: CreateRoute,
  LoginRoute: LoginRoute,
  RSlugEditRoute: RSlugEditRoute,
  RSlugIndexRoute: RSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
